post http://localhost:3000/register 
Content-Type: application/json 

{
    "username" : "abhishek",
    "name" : "Abhishek kumar",
    "password" : "rich_man_999",
    "gender" : "male",
    "location" : "Detroit"
}

###
post http://localhost:3000/login 
Content-Type: application/json 

{
  "username": "adam_richard",
  "password": "richard_567"
} 

###
put http://localhost:3000/change-password
Content-Type: application/json 

{
  "username": "adam_richard",
  "oldPassword": "richard_56",
  "newPassword": "richard@123"
}